### PR TITLE
Fixed selectors for some class changes that Github made

### PR DESCRIPTION
**Pull request by csudcy**
Github decided to change some CSS classes so I've updated the selectors used in the script.
I've tested it using Tampermonkey on Chrome with pulls, commits and compares.
Also, updated the version so it will get auto updated.

### CODE REVIEW

**Comment by jakub-g** [comment]
Awesome, I've seen it breaking this week but I had no time to investigate it.

Quickly looking at the PR, please also change the version from 1.0.3 to 1.0.4 in both files, and update `CHANGELOG.txt` accordingly

I'll test it later and merge if it's fine

Thanks!

**Comment by jakub-g** [comment]
Oh, actually I'd prefer to have a version-bump as a separate commit  like here

https://github.com/jakub-g/gh-code-review-assistant/commit/c64070961b77ea7b5ffc748e5cf89ec12ce2413c

so that it's easily visible when I do git log

https://github.com/jakub-g/gh-code-review-assistant/commits/next

**Comment by csudcy** [comment]
Cool; hope that's good now :+1:

**Comment by jakub-g** [comment]
Merged and pushed to master, should now auto-update for all the users. Thanks!

**Comment by csudcy** [comment]
Awesome :smiley: BTW, thank you for making a very useful tool which, IMHO, should be a builtin feature of Github!

**Comment by jakub-g** [comment]
Feel invited to let others know and star the project ;)

**Pull request merged**
